int myStrlen(char T[]);
char *myStrcpy(char * Tdest, char * Tsrc);
void affichageEnHexadecimal(char T[]);
void affichageEnDecimal(char T[]);
char * mettreEnMajuscule(char T[]);
char * mettreEnMinuscule(char T[]);
char * transformerMinMaj(char T[]);
char * retournerMot(char T[]);
int rechercherCaractereG(char T[], char a);
int rechercherCaractereD(char T[], char a);
int estPalindrome(char T[], int d, int f);
int comparerChaine(char T1[], char T2[]);
long int valeurDecimale(char T1[]);
void retournerChaine(char T1[]);
void intVersChaine(int nombre, char T1[]);
